### PR TITLE
chore(deps): upgrade to react 18

### PR DESCRIPTION
**Pull request by yulinscottkang**
- Add `.prettierrc` for a consistent formatting
- Use conventional config for commitlint since `chore` is missing from the angular config
- Upgrade `devDependencies` to react 18
- Update `peerDependencies` to support react 18
- Delete `@testing-library/react-hooks` since `renderHook` is now included in `@testing-library/react` ([ref](https://github.com/testing-library/react-testing-library/pull/991))
- Fix `AzureMapContext.test.tsx` by wrapping component updates in `act()`  
- Update types.ts for react 18 ([ref](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210))
  -  `StatelessComponent` -> `FunctionComponent`
  - `IAzureMapFeature` -> `(IAzureMapFeature & ReactNode)`

### CODE REVIEW

**Comment by rvdkooy** [comment]
Hi, does this work well with react 18 strict mode?
I tried this myself a whille ago and I remember running into some issues with it.
something in the line of: `Uncaught Error: 'datasource-id' is already added to the map`

it seems like not everything is being cleaned up after unmounting and then throws (which is the whole purpose of strictmode)

maybe I can help out a bit on this....

**Review by dubiety — APPROVED** [review]

**Comment by yulinscottkang** [comment]
> Hi, does this work well with react 18 strict mode? I tried this myself a whille ago and I remember running into some issues with it. something in the line of: `Uncaught Error: 'datasource-id' is already added to the map`
> 
> it seems like not everything is being cleaned up after unmounting and then throws (which is the whole purpose of strictmode)
> 
> maybe I can help out a bit on this....

Hi @rvdkooy, this PR doesn't fix and modify anything related to strict mode. It would be great if you could provide help or elaborate on the issue, thanks!

**Comment by rvdkooy** [comment]
Hi @yulinscottkang 
I will look into this and see what is needed for this
thanks

**Comment by rvdkooy** [comment]
@yulinscottkang see: https://github.com/Azure/react-azure-maps/pull/126

**Pull request merged**
